version: '3.3'

services:
  jupyterlab:
    build: .
    image: ken2s/jupyterlab
    container_name: jupyterlab
    user: $NB_USER
    working_dir: /home/$NB_USER/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
      - NB_USER=$NB_USER
      - NB_UID=$NB_UID
      - NB_GID=$NB_GID
      - JAVA_HOME=$JAVA_HOME
    volumes:
      - ~/notebooks:/home/$NB_USER/notebooks
    network_mode: "host"
    # ports:
    #   - 8888:8888
